#!/bin/bash

# Pull the image from Docker Hub
docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
docker pull amittz98/img-dev:latest

sudo docker run -d --name dev-con -p 5000:5000 img-dev:latest
